#!/bin/bash

COMPOSE_CMD=$1
shift
DOCKER_COMPOSE_FILE="docker-compose-no-frontend.dev.yml"

while [[ $# -gt 0 ]]; do
  case $1 in
    -f|--frontend)
      DOCKER_COMPOSE_FILE="docker-compose.dev.yml"
      echo "using frontend"
      shift # past argument
      ;;
    *)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

RUN_CMD=""

# TODO: add args to choose which docker-compose file to use (dev/frontend/no frontend)
# add (if $1==up, then add --detach flag to cmd)
if [ "$COMPOSE_CMD" == "up" ]; then
  RUN_CMD="up --detach"
elif [ "$COMPOSE_CMD" == "down" ]; then
  RUN_CMD="down"
fi

pwd
echo ${RUN_CMD}
# shellcheck disable=SC2027
docker compose -f ${DOCKER_COMPOSE_FILE} -p grocery-organizer ${RUN_CMD}